apiVersion: v2
name: devpro-salesportal
description: Helm chart for Devpro Sales Portal
type: application
version: 0.2.7
appVersion: "1.1.18203306613"
dependencies:
  - name: mongodb
    version: 16.5.45   # MongoDB 8.0.13
    repository: https://charts.bitnami.com/bitnami
    alias: mongodb
    condition: mongodb.enabled
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
