front:
  enabled: true
  host: sales-portal.random
  name: salesportal-wasmapp
  image: docker.io/devprofr/salesportal-wasmapp
  tag: 1.1.7818547414
  port: 80
  replicaCount: 1
  healthEndpoint: /health
  db: {}
  extraEnv: []
    # - name: xxx
    #   value: "yyyy"
  additionalPodLabels: {}
  api: {}
  tls: {}
    # secretName: chart-example-tls
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 64Mi

adapter:
  enabled: true
  host: crm-adapter.random
  name: salesportal-crmadapterwebapi
  image: docker.io/devprofr/salesportal-crmadapterwebapi
  tag: 1.1.7818547414
  replicaCount: 1
  port: 8080
  healthEndpoint: /health
  db: {}
  extraEnv: []
  additionalPodLabels: {}
  tls: {}
  resources: {}

data:
  enabled: true
  host: crm-data.random
  name: salesportal-crmdatawebapi
  image: docker.io/devprofr/salesportal-crmdatawebapi
  tag: 1.1.7818547414
  replicaCount: 1
  port: 8080
  healthEndpoint: /health
  db:
    connectionString: ""
    databaseName: ""
  extraEnv: []
  additionalPodLabels: {}
  tls: {}
  resources: {}

dotnet:
  environment: Production
  logLevel: Information
  enableSwagger: false
  enableOpenTelemetry: false
  skipCertificateValidation: false

ingress:
  enabled: false
  className: ""
  annotations: {}

mongodb:
  enabled: false
  # https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml
  auth: {}
