apiVersion: v2
name: drupal
description: Drupal Web Application - for container security workshops
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - security
  - vulnerable
  - workshop
  - training
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
