apiVersion: v2
name: r2devops
description: Helm chart for managing R2Devops
type: application
version: "0.1.1"
appVersion: "1.14.1"
dependencies:
  - name: r2devops
    version: 0.2.3
    repository: https://charts.r2devops.io
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
home: https://github.com/devpro/helm-charts/tree/main/charts/r2devops
