k10: {}
  # global:
  #   persistence:
  #     storageClass: <storage-class-name>
  # externalGateway:
  #   create: true
  # auth:
  #   tokenAuth:
  #     enabled: true
  # route:
  #   enabled: true
  #   host: <A FQDN of your choice with proper DNS entry>
  #   path: "/<custom-path>"
  #   tls:
  #     enabled: true
  #     termination: <reencrypt/edge/passthrough>
  #     insecureEdgeTerminationPolicy: <disable/redirect/allow>
  # prometheus:
  #   server:
  #     baseURL: "/<custom-path>/prometheus/"
  #     prefixURL: "/<custom-path>/prometheus/"
