{{- $applications := list .Values.blazorapp .Values.webapi -}}
{{ range $applications }}
{{- $name := .name -}}
{{- if .enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .name }}
      app.kubernetes.io/name: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        {{- if .additionalPodLabels }}
        {{- toYaml .additionalPodLabels | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ .tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
          resources:
            {{- toYaml .resources | nindent 12 }}
          env:
          {{- if .extraEnv }}
            {{- toYaml .extraEnv | nindent 12 }}
          {{- end }}
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ $.Values.dotnet.environment }}"
            - name: Logging__LogLevel__Default
              value: {{ $.Values.dotnet.logLevels.default }}
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: {{ $.Values.dotnet.logLevels.framework }}
            - name: Logging__LogLevel__Devpro
              value: {{ $.Values.dotnet.logLevels.application }}
            {{- if $.Values.dotnet.httpsRedirectionEnabled }}
            - name: Features__IsHttpsRedirectionEnabled
              value: "true"
            {{- end }}
            {{- if $.Values.dotnet.scalarEnabled }}
            - name: Features__IsScalarEnabled
              value: "true"
            {{- end }}
            {{- if eq .role "frontend" }}
            - name: WebApi__BaseUrl
              value: "http://{{ $.Values.webapi.name }}"
            - name: Firebase__WebAppConfiguration__ApiKey
              value: "{{ $.Values.firebase.webApp.apiKey }}"
            - name: Firebase__WebAppConfiguration__AuthDomain
              value: "{{ $.Values.firebase.webApp.projectId }}.firebaseapp.com"
            - name: Firebase__WebAppConfiguration__ProjectId
              value: "{{ $.Values.firebase.webApp.projectId }}"
            - name: Firebase__ServiceAccount
              value:  {{ $.Values.firebase.serviceAccount | toJson | quote }}
            {{- else if eq .role "backend" }}
            - name: AllowedOrigins__0
              value: "https://{{ $.Values.blazorapp.host }}"
            - name: AllowedOrigins__0
              value: "http://{{ $.Values.blazorapp.name }}"
            - name: Authentication__JwtBearer__Authority
              value: "https://securetoken.google.com/{{ $.Values.firebase.webApp.projectId }}"
            - name: Authentication__JwtBearer__TokenValidation__Audience
              value: "{{ $.Values.firebase.webApp.projectId }}"
            - name: Authentication__JwtBearer__TokenValidation__Issuer
              value: "https://securetoken.google.com/{{ $.Values.firebase.webApp.projectId }}"
            - name: Infrastructure__MongoDB__ConnectionString
              value: {{ .db.connectionString }}
            - name: Infrastructure__MongoDB__DatabaseName
              value: {{ .db.databaseName }}
            {{- end }}
      restartPolicy: Always
{{- end }}
{{ end }}
