{{- $applications := list .Values.blazorapp .Values.webapi -}}
{{ range $applications }}
{{- if .enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
    {{- include "keeptrack.commonLabels" (dict "app" . "root" $) | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .name }}
      app.kubernetes.io/name: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        app.kubernetes.io/name: {{ .name }}
        {{- include "keeptrack.commonLabels" (dict "app" . "root" $) | nindent 8 }}
        {{- if .additionalPodLabels }}
        {{- toYaml .additionalPodLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if $.Values.security.serviceAccount.create }}
      serviceAccountName: {{ .name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      automountServiceAccountToken: false
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $.Values.security.hardened.enabled }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- end }}
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ .tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
          resources:
            {{- toYaml .resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1654   # "app" user
            runAsGroup: 1654  # "app" group
            allowPrivilegeEscalation: false
            {{- if $.Values.security.hardened.enabled }}
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            {{- end }}
          {{- if $.Values.security.hardened.enabled }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- end }}
          env:
          {{- if $.Values.security.hardened.enabled }}
            - name: HOME
              value: /tmp
          {{- end }}
          {{- if .extraEnv }}
            {{- toYaml .extraEnv | nindent 12 }}
          {{- end }}
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ $.Values.dotnet.environment }}"
            - name: Logging__LogLevel__Default
              value: {{ $.Values.dotnet.logLevels.default | quote }}
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: {{ $.Values.dotnet.logLevels.framework | quote }}
            - name: Logging__LogLevel__Keeptrack
              value: {{ $.Values.dotnet.logLevels.application | quote }}
            - name: Features__IsHttpsRedirectionEnabled
              value: {{ $.Values.dotnet.httpsRedirectionEnabled | quote }}
            - name: Features__IsScalarEnabled
              value: {{ $.Values.dotnet.scalarEnabled | quote }}
            {{- if eq .role "frontend" }}
            - name: WebApi__BaseUrl
              value: "http://{{ $.Values.webapi.name }}"
            - name: Features__IsWebSocketsOnlyEnabled
              value: {{ .webSocketsOnly | quote }}
            {{- if .dataProtection.enabled }}
            {{- if .dataProtection.connectionStringSecretKeyRef }}
            - name: DataProtection__MongoDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .dataProtection.connectionStringSecretKeyRef.name }}
                  key: {{ .dataProtection.connectionStringSecretKeyRef.key }}
            {{- else }}
            - name: DataProtection__MongoDb__ConnectionString
              value: {{ .dataProtection.connectionString | quote }}
            {{- end }}
            - name: DataProtection__MongoDb__DatabaseName
              value: {{ .dataProtection.databaseName | quote }}
            {{- end }}
            {{- if $.Values.firebase.webApp.apiKeySecretKeyRef }}
            - name: Firebase__WebAppConfiguration__ApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.firebase.webApp.apiKeySecretKeyRef.name }}
                  key: {{ $.Values.firebase.webApp.apiKeySecretKeyRef.key }}
            {{- else }}
            - name: Firebase__WebAppConfiguration__ApiKey
              value: "{{ $.Values.firebase.webApp.apiKey }}"
            {{- end }}
            {{- if $.Values.firebase.webApp.authDomainSecretKeyRef }}
            - name: Firebase__WebAppConfiguration__AuthDomain
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.firebase.webApp.authDomainSecretKeyRef.name }}
                  key: {{ $.Values.firebase.webApp.authDomainSecretKeyRef.key }}
            {{- else }}
            - name: Firebase__WebAppConfiguration__AuthDomain
              value: "{{ $.Values.firebase.webApp.authDomain }}"
            {{- end }}
            {{- if $.Values.firebase.webApp.projectIdSecretKeyRef }}
            - name: Firebase__WebAppConfiguration__ProjectId
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.firebase.webApp.projectIdSecretKeyRef.name }}
                  key: {{ $.Values.firebase.webApp.projectIdSecretKeyRef.key }}
            {{- else }}
            - name: Firebase__WebAppConfiguration__ProjectId
              value: "{{ $.Values.firebase.webApp.projectId }}"
            {{- end }}
            {{- if $.Values.firebase.serviceAccountSecretKeyRef }}
            - name: Firebase__ServiceAccount
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.firebase.serviceAccountSecretKeyRef.name }}
                  key: {{ $.Values.firebase.serviceAccountSecretKeyRef.key }}
            {{- else }}
            - name: Firebase__ServiceAccount
              value: {{ $.Values.firebase.serviceAccount | toJson | quote }}
            {{- end }}
            {{- else if eq .role "backend" }}
            - name: AllowedOrigins__0
              value: "https://{{ $.Values.blazorapp.host }}"
            - name: AllowedOrigins__1
              value: "http://{{ $.Values.blazorapp.name }}"
            {{- if $.Values.firebase.auth.authoritySecretKeyRef }}
            - name: Authentication__JwtBearer__Authority
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.firebase.auth.authoritySecretKeyRef.name }}
                  key: {{ $.Values.firebase.auth.authoritySecretKeyRef.key }}
            {{- else }}
            - name: Authentication__JwtBearer__Authority
              value: "https://securetoken.google.com/{{ $.Values.firebase.webApp.projectId }}"
            {{- end }}
            {{- if $.Values.firebase.webApp.projectIdSecretKeyRef }}
            - name: Authentication__JwtBearer__TokenValidation__Audience
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.firebase.webApp.projectIdSecretKeyRef.name }}
                  key: {{ $.Values.firebase.webApp.projectIdSecretKeyRef.key }}
            {{- else }}
            - name: Authentication__JwtBearer__TokenValidation__Audience
              value: "{{ $.Values.firebase.webApp.projectId }}"
            {{- end }}
            {{- if $.Values.firebase.auth.authoritySecretKeyRef }}
            - name: Authentication__JwtBearer__TokenValidation__Issuer
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.firebase.auth.authoritySecretKeyRef.name }}
                  key: {{ $.Values.firebase.auth.authoritySecretKeyRef.key }}
            {{- else }}
            - name: Authentication__JwtBearer__TokenValidation__Issuer
              value: "https://securetoken.google.com/{{ $.Values.firebase.webApp.projectId }}"
            {{- end }}
            {{- if .db.connectionStringSecretKeyRef }}
            - name: Infrastructure__MongoDB__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .db.connectionStringSecretKeyRef.name }}
                  key: {{ .db.connectionStringSecretKeyRef.key }}
            {{- else }}
            - name: Infrastructure__MongoDB__ConnectionString
              value: {{ .db.connectionString | quote }}
            {{- end }}
            - name: Infrastructure__MongoDB__DatabaseName
              value: {{ .db.databaseName | quote }}
            - name: Features__IsReferenceSyncEnabled
              value: {{ .referenceData.isSyncEnabled | quote }}
            - name: Features__FreeTierItemLimit
              value: {{ .freeTierItemLimit | quote }}
            {{- if .referenceData.bookProvider }}
            - name: ReferenceData__BookProvider
              value: {{ .referenceData.bookProvider | quote }}
            {{- end }}
            {{- if .referenceData.tmdb.apiKeySecretKeyRef }}
            - name: Tmdb__ApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ .referenceData.tmdb.apiKeySecretKeyRef.name }}
                  key: {{ .referenceData.tmdb.apiKeySecretKeyRef.key }}
            {{- else }}
            - name: Tmdb__ApiKey
              value: {{ .referenceData.tmdb.apiKey | quote }}
            {{- end }}
            {{- if .referenceData.rawg.apiKeySecretKeyRef }}
            - name: Rawg__ApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ .referenceData.rawg.apiKeySecretKeyRef.name }}
                  key: {{ .referenceData.rawg.apiKeySecretKeyRef.key }}
            {{- else }}
            - name: Rawg__ApiKey
              value: {{ .referenceData.rawg.apiKey | quote }}
            {{- end }}
            {{- if .referenceData.discogs.tokenSecretKeyRef }}
            - name: Discogs__Token
              valueFrom:
                secretKeyRef:
                  name: {{ .referenceData.discogs.tokenSecretKeyRef.name }}
                  key: {{ .referenceData.discogs.tokenSecretKeyRef.key }}
            {{- else }}
            - name: Discogs__Token
              value: {{ .referenceData.discogs.token | quote }}
            {{- end }}
            {{- if .referenceData.googlebooks.apiKeySecretKeyRef }}
            - name: GoogleBooks__ApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ .referenceData.googlebooks.apiKeySecretKeyRef.name }}
                  key: {{ .referenceData.googlebooks.apiKeySecretKeyRef.key }}
            {{- else }}
            - name: GoogleBooks__ApiKey
              value: {{ .referenceData.googlebooks.apiKey | quote }}
            {{- end }}
            {{- if .referenceData.omdb.apiKeySecretKeyRef }}
            - name: Omdb__ApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ .referenceData.omdb.apiKeySecretKeyRef.name }}
                  key: {{ .referenceData.omdb.apiKeySecretKeyRef.key }}
            {{- else }}
            - name: Omdb__ApiKey
              value: {{ .referenceData.omdb.apiKey | quote }}
            {{- end }}
            {{- if .referenceData.igdb.clientIdSecretKeyRef }}
            - name: Igdb__ClientId
              valueFrom:
                secretKeyRef:
                  name: {{ .referenceData.igdb.clientIdSecretKeyRef.name }}
                  key: {{ .referenceData.igdb.clientIdSecretKeyRef.key }}
            {{- else }}
            - name: Igdb__ClientId
              value: {{ .referenceData.igdb.clientId | quote }}
            {{- end }}
            {{- if .referenceData.igdb.clientSecretSecretKeyRef }}
            - name: Igdb__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: {{ .referenceData.igdb.clientSecretSecretKeyRef.name }}
                  key: {{ .referenceData.igdb.clientSecretSecretKeyRef.key }}
            {{- else }}
            - name: Igdb__ClientSecret
              value: {{ .referenceData.igdb.clientSecret | quote }}
            {{- end }}
            {{- end }}
      restartPolicy: Always
      {{- if $.Values.security.hardened.enabled }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- end }}
{{- end }}
{{ end }}
