apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dvwa.fullname" . }}-secret
  labels:
    {{- include "dvwa.labels" . | nindent 4 }}
type: Opaque
stringData:
  mariadb-root-password: {{ .Values.mariadb.rootPassword | quote }}
  mariadb-password: {{ .Values.mariadb.password | quote }}
  dvwa-admin-username: {{ .Values.dvwa.adminUsername | quote }}
  dvwa-admin-password: {{ .Values.dvwa.adminPassword | quote }}
