apiVersion: v2
name: promyze
description: Helm chart for managing Promyze
type: application
version: "0.1.0"
appVersion: "4.12.1"
dependencies:
  - name: promyze
    version: 0.3.4
    repository: https://promyze.github.io/helm-charts
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
home: https://github.com/devpro/helm-charts/tree/main/charts/promyze
