# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
jenkins:
  controller:
    adminUser: "admin"
    admin:
      existingSecret: ""
      userKey: jenkins-admin-user
      passwordKey: jenkins-admin-password
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "2048Mi"
