{{- $applications := list .Values.webapi -}}
{{ range $applications }}
{{- $app := . -}}
{{- if and $.Values.ingress.enabled .enabled -}}
{{- include "terraform-backend-mongodb.validateValues" $ }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
  labels:
    app: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
    app.kubernetes.io/name: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
    {{- include "terraform-backend-mongodb.commonLabels" (dict "app" . "root" $) | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
                port:
                  number: {{ .port }}
    {{- range .ingressExtraHosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "terraform-backend-mongodb.fullname" (dict "app" $app "root" $) }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
  {{- if .tls }}
  tls:
    - hosts:
        - {{ .host | quote }}
      secretName: {{ .tls.secretName }}
  {{- end }}
{{- end }}
{{ end }}
