{{- include "terraform-backend-mongodb.validateValues" . }}
{{- $applications := list .Values.webapi -}}
{{ range $applications }}
{{- if and .enabled (not .db.connectionStringSecretKeyRef) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}-db
  labels:
    app: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
    app.kubernetes.io/name: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
    {{- include "terraform-backend-mongodb.commonLabels" (dict "app" . "root" $) | nindent 4 }}
type: Opaque
stringData:
  connectionString: {{ include "terraform-backend-mongodb.mongoConnectionString" $ | quote }}
{{- end }}
{{ end }}
