{{- $applications := list .Values.webapi -}}
{{ range $applications }}
{{- if .enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
  name: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
{{- end }}
{{ end }}
