{{- if .Values.security.serviceAccount.create }}
{{- $applications := list .Values.webapi -}}
{{ range $applications }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
  labels:
    app: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
    app.kubernetes.io/name: {{ include "terraform-backend-mongodb.fullname" (dict "app" . "root" $) }}
    {{- include "terraform-backend-mongodb.commonLabels" (dict "app" . "root" $) | nindent 4 }}
automountServiceAccountToken: false
{{ end }}
{{- end }}
