apiVersion: v2
name: mariadb
description: Helm chart for managing MariaDB
type: application
version: "0.1.0"
appVersion: "10.6.11"
dependencies:
  - name: mariadb
    version: 11.3.5
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
