{{- if .Values.security.serviceAccount.create }}
{{- $applications := list .Values.webapp -}}
{{ range $applications }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
{{ end }}
{{- end }}
