apiVersion: v2
name: keeptrack
description: Helm chart for Keeptrack
type: application
version: 0.1.0
appVersion: "1.1.18203306613"
dependencies:
  - name: mongodb
    version: 18.6.16   # MongoDB 8.2.6
    repository: https://charts.bitnami.com/bitnami
    alias: mongodb
    condition: mongodb.enabled
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
