apiVersion: v2
name: keeptrack
description: Helm chart for Keeptrack
type: application
version: 0.2.2
appVersion: "2.1"
home: https://github.com/devpro/keeptrack
sources:
  - https://github.com/devpro/keeptrack
keywords:
  - keeptrack
dependencies:
  - name: mongodb
    version: 18.6.16   # MongoDB 8.2.6
    repository: https://charts.bitnami.com/bitnami
    alias: mongodb
    condition: mongodb.enabled
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
