blazorapp:
  enabled: true
  role: frontend
  name: keeptrack-blazorapp
  image: docker.io/devprofr/keeptrack-blazorapp
  port: 80
  containerPort: 8080
  healthEndpoint: /health
  tls:
    secretName: keeptrack-blazorapp-tls
  # optional
  tag: 1.1.23099092819      # ref. https://hub.docker.com/r/devprofr/keeptrack-blazorapp/tags
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 64Mi
  extraEnv: []
    # - name: xxx
    #   value: "yyyy"
  additionalPodLabels: {}
  # mandatory
  host: ""

webapi:
  enabled: true
  role: backend
  name: keeptrack-webapi
  image: docker.io/devprofr/keeptrack-webapi
  port: 80
  containerPort: 8080
  healthEndpoint: /health
  tls:
    secretName: keeptrack-webapi-tls
  # optional
  host: ""
  replicaCount: 1
  tag: 1.1.23099092819    # ref. https://hub.docker.com/r/devprofr/keeptrack-webapi/tags
  resources: {}
  extraEnv: []
  additionalPodLabels: {}
  # mandatory
  db:
    # important: connectionString or connectionStringSecretKeyRef must be provided
    # connectionStringSecretKeyRef:
    #   name: ""
    #   key: ""
    # connectionString: "someconnstring"
    databaseName: "keeptrack"

dotnet:
  environment: Production
  logLevels:
    default: Information
    framework: Information
    application: Information
  scalarEnabled: false
  httpsRedirectionEnabled: false

security:
  serviceAccount:
    create: false

# mandatory
firebase:
  auth: {}
    # authoritySecretKeyRef:
    #   name: ""
    #   key: ""
    # apiKey: ""
  webApp: {}
    # apiKeySecretKeyRef:
    #   name: ""
    #   key: ""
    # apiKey: ""
    # authDomainSecretKeyRef:
    #   name: ""
    #   key: ""
    # authDomain: ""
    # projectIdSecretKeyRef:
    #   name: ""
    #   key: ""
    # projectId: ""
  # serviceAccountSecretKeyRef:
    #   name: ""
    #   key: ""
  # serviceAccount:
  #   type: "service_account"
  #   project_id: ""
  #   private_key_id: ""
  #   private_key: ""
  #   client_email: ""
  #   client_id: ""
  #   auth_uri: ""
  #   token_uri: ""
  #   auth_provider_x509_cert_url: ""
  #   client_x509_cert_url: ""
  #   universe_domain: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-prod

# embedded chart configuration: https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml
mongodb:
  enabled: false
  global:
  #   imageRegistry: ""
  #   imagePullSecrets: []
  #   defaultStorageClass: ""
  #   storageClass: ""
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnami/mongodb     # other options: chainguard/mongodb
    tag: latest                     # IMPORTANT: latest should never be used in Production
  auth: {}
    # rootPassword: ""
    # existingSecret: ""
