# https://github.com/reportportal/kubernetes/blob/develop/reportportal/values.yaml
reportportal:
  # https://github.com/elastic/helm-charts/blob/main/elasticsearch/values.yaml
  elasticsearch: {}
  # https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml
  minio: {}
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  postgresql: {}
  # https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml
  rabbitmq: {}
