apiVersion: v2
name: wordpress
description: Helm chart for managing WordPress
type: application
version: "0.1.1"
appVersion: "6.1.0"
dependencies:
  - name: wordpress
    version: 15.2.14
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
