---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: concourse-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-poc
spec:
  tls:
    - hosts:
        - my-domain.com
      secretName: domain-web-tls
  rules:
    - host: my-domain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: concourse-stable-web
              servicePort: 8080
