apiVersion: v2
name: keycloak
description: Helm chart for managing Keycloak
type: application
version: "0.2.0"
appVersion: "23.0.6"
dependencies:
  - name: keycloak
    version: 18.7.0
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
