apiVersion: v2
name: devpro-charts/ingress-nginx
description: Helm chart for managing NGINX Ingress Controller
type: application
version: "0.1.1"
appVersion: "1.4.0"
dependencies:
  - name: ingress-nginx
    version: 4.3.0
    repository: https://kubernetes.github.io/ingress-nginx
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
