{{- $name := $.Values.name -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
