{{- if .Values.ingress.enabled }}
{{- include "sidelab.validateValues" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sidelab.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sidelab.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ include "sidelab.ingressHost" . | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ include "sidelab.ingressHost" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sidelab.fullname" . }}
                port:
                  name: http
{{- end }}
