{{- include "sidelab.validateValues" . }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sidelab.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sidelab.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ include "sidelab.jwtSecret" . | quote }}
  ADMIN_USERNAME: {{ .Values.auth.adminUsername | quote }}
  ADMIN_PASSWORD: {{ include "sidelab.adminPassword" . | quote }}
{{- end }}
{{- if and (eq .Values.database.backend "mongo") (not .Values.database.mongo.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sidelab.mongoSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sidelab.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ include "sidelab.mongoUrl" . | quote }}
{{- end }}
