name:
# cluster type (enums: gke)
type:
replicas: 1
network:
  pods:
    cidrBlocks:
      - 192.168.0.0/16
googlecloud:
  # project ID
  project:
  # region name (example: europe-west1)
  region:
  # zone name
  zone:
  # VPC name
  vpc:
  # subnet
  subnet:
    name:
    cidr: "172.20.0.0/16"
