image:
  repository: ghcr.io/devpro/nextportal
  tag: "0.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
  # - name: ""

replicaCount: 1

podAnnotations: {}

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 500m
  #   memory: 512Mi

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  # e.g. traefik
  className: ""
  domain: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  tls:
    enabled: false

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

podSecurityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1001
  # runAsGroup: 1001
  # fsGroup: 1001

containerSecurityContext: {}
  # allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: false
  # capabilities:
  #   drop:
  #     - ALL

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

nodeSelector: {}
tolerations: []
affinity: {}

networkpolicy:
  enabled: false

env:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"

# envFrom:
#   - secretRef:
#       name: ""
