name: cow-demo
image: monachus/rancher-demo
tag: latest
replicaCount: 2
host: "cow-demo.example.com"
ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
tls:
  secretName: "cow-demo-tls"
cow:
  color: red
