name: cow-demo
image: monachus/rancher-demo
tag: v1.4.1
replicaCount: 2
port: 80
ingress:
  enabled: false
  className: "nginx"
  host: ""
  annotations: {}
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    secretName: "cow-demo-tls"
cow:
  color: red
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 64Mi
