{{- if eq .Values.cloudprovider "exoscale" }}
{{- range $index, $nodepool := .Values.nodepools }}
---
# Exoscale configuration (ref. exoscaleconfigs.rke-machine-config.cattle.io CRD)
apiVersion: rke-machine-config.cattle.io/v1
kind: ExoscaleConfig
metadata:
  name: {{ $nodepool.name }}
  namespace: fleet-default
  # annotations:
  #   key: string
{{- if $nodepool.labels }}
  labels:
{{ toYaml $nodepool.labels | indent 4 }}
{{- end }}
# affinityGroup:
#   - string
# apiKey: string
# apiSecretKey: string
# availabilityZone: string
# diskSize: string
image: {{ $nodepool.image }}
# instanceProfile: string
# securityGroup:
#   - string
# sshKey: string
sshUser: {{ $nodepool.sshUser }}
# url: string
userdata: {{ $nodepool.userdata }}
{{- end }}
{{- end }}
