{{- $name := $.Values.name -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
  name: {{ $name }}-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
