{{- if .Values.admin.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trackboard.fullname" . }}
  labels:
    {{- include "trackboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ .Values.admin.password }}
{{- end }}
