# https://github.com/neuvector/neuvector-helm/blob/master/charts/core/values.yaml
core:
  controller:
    replicas: 2
  cve:
    scanner:
      replicas: 2
  manager:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls: true
      secretName: neuvector-tls
