{{- if $.Values.azureCloudConfig.encryptedData -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: azure-cloud-provider
  namespace: kube-system
spec:
  encryptedData:
    cloud-config: {{ $.Values.azureCloudConfig.encryptedData }}
  template:
    metadata:
      name: azure-cloud-provider
      namespace: kube-system
    type: Opaque
{{- end }}
