{{- if $.Values.azureFile.enabled -}}
---
# https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  skuName: {{ $.Values.azureFile.skuName }}
  location: {{ $.Values.azureFile.location }}
  storageAccount: {{ $.Values.azureFile.storageAccount }}
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
{{- end }}
