apiVersion: v2
name: longhorn
description: Helm chart for managing Longhorn
type: application
version: "0.1.2"
appVersion: "1.4.0"
dependencies:
  - name: longhorn
    version: 1.4.0
    repository: https://charts.longhorn.io
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
