{{- $applications := list .Values.backend .Values.frontend .Values.nodejsApi -}}
{{ range $applications }}
{{- $name := .name -}}
{{- if .enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
      app.kubernetes.io/name: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        {{- if .additionalPodLabels }}
        {{- toYaml .additionalPodLabels | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ .tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- with .env }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            # TODO: only do this for .NET apps
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ $.Values.aspnetcore.environment }}"
            - name: AllowedOrigins__0
              value: "http://{{ $.Values.frontend.host }}"
            - name: AllowedOrigins__1
              value: "https://{{ $.Values.frontend.host }}"
            - name: OpenTelemetry__CollectorEndpoint
              value: "{{ $.Values.otelCollector.endpoint }}"
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{ end }}
