{{- $applications := list .Values.backend .Values.frontend -}}
{{ range $applications }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
      app.kubernetes.io/name: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        app.kubernetes.io/name: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ .tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          {{- with .env }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            # TODO: only do this for .NET apps
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ $.Values.aspnetcore.environment }}"
            - name: AllowedOrigins__0
              value: "http://{{ $.Values.frontend.host }}"
            - name: AllowedOrigins__1
              value: "https://{{ $.Values.frontend.host }}"
            - name: OpenTelemetry__CollectorEndpoint
              value: "{{ $.Values.otelCollector.endpoint }}"
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{ end }}
