{{- $applications := list .Values.backend .Values.frontend .Values.nodejsApi .Values.legacy -}}
{{ range $applications }}
{{- $name := .name -}}
{{- if and $.Values.ingress.enabled .enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-ingress
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}-svc
                port:
                  number: 80
    {{- range .ingressExtraHosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $name }}-svc
                port:
                  number: 80
          {{- end }}
    {{- end }}
  {{- if .tls }}
  tls:
    - hosts:
        - {{ .host | quote }}
      secretName: {{ .tls.secretName }}
  {{- end }}
{{- end }}
{{ end }}
