---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
      app.kubernetes.io/name: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        {{- if .additionalPodLabels }}
        {{- toYaml .additionalPodLabels | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]
              {{- if .nodeAffinity.os }}
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - {{ .nodeAffinity.os }}
              {{- end }}
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ .tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .healthEndpoint }}
          livenessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
            {{- if .livenessProbeConfig }}
            {{- toYaml .livenessProbeConfig | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: http
            {{- if .readinessProbeConfig }}
            {{- toYaml .readinessProbeConfig | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- with .env }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            {{- toYaml . | nindent 12 }}
          {{- end }}
