{{- if eq .Values.type "gke" }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: {{ .Values.name }}-control-plane
spec:
  location: {{ .Values.googlecloud.region }}
  project: {{ .Values.googlecloud.project }}
  # releaseChannel: "regular"
{{- end }}
