cluster:
  name: CLUSTER_NAME

cloudprovider: azure

cloudCredentialSecretName: CLOUD_CREDENTIAL_SECRET  # Azure Cloud Credential (example: cattle-global-data:<secret-id>)

nodepools:
  - etcd: true
    controlplane: true
    worker: true
    annotations: {}
    labels: {}
    quantity: 1
    paused: false
    name: nodepool-1
    region: westus
    machineImage: "Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:20.04.202307240"
    instanceType: Standard_DS2_v2
    storageType: Standard_LRS
    sshUser: azureuser
    openPorts:
      - 6443/tcp    # Kubernetes API
      - 2379/tcp    # etcd client port
      - 2380/tcp    # etcd peer port
      - 10250/tcp   # kubelet
    availabilitySet: "avs-AZURE_PREFIX"
    azureEnvironment: AzurePublicCloud
    managedDisks: true
    networkSecurityGroup: "nsg-AZURE_PREFIX"
    resourceGroup: "rg-AZURE_PREFIX"
    subnet: rke2
    subnetPrefix: "192.168.0.0/16"
    virtualNetwork: "vnet-AZURE_PREFIX"
