{{ range .Values.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
spec:
  {{- if .encryptedValue }}
  encryptedData:
    {{ .key }}: {{ .encryptedValue }}
  {{- end }}
  template:
    metadata:
      name: {{ .name }}
{{ end }}
