{{- $sealedSecrets := list .Values.secrets.wordpressPassword -}}
{{ range $sealedSecrets }}
{{- if .encryptedValue }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
spec:
  encryptedData:
    {{ .key }}: {{ .encryptedValue }}
  template:
    metadata:
      name: {{ .name }}
{{- end }}
{{ end }}
