{{ range .Values.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
spec:
  {{- if .encryptedData }}
  ingressClassName: {{ .encryptedData }}
  encryptedData:
  {{- end }}
  template:
    metadata:
      name: {{ .name }}
{{ end }}
