apiVersion: v2
name: rancher-cluster-templates
description: Helm chart for managing Rancher cluster templates
type: application
version: "0.1.2"
appVersion: "0.1.0"
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
home: https://github.com/devpro/helm-charts/tree/main/charts/rancher-cluster-templates
