# cluster specific values
cluster:
  # cluster name
  name: ""
  # cluster labels
  labels: {}
  # cluster annotations
  annotations: {}

# cloud credential secret name (do not need to be provided if using custom driver)
cloudCredentialSecretName: ""

# cloud provider name (values can be amazonec2, azure, digitalocean, harvester, vsphere)
cloudprovider: ""

# kubernetes version
kubernetesVersion: "v1.24.14+rke2r1"

# RKE (Rancher Kubernetes Engine, Kubernetes distribution) options
rke:
  # enable local auth endpoint
  localClusterAuthEndpoint:
    enabled: false
  # specify fqdn of local access endpoint
  # fqdn: foo.bar.example
  # specify cacert of local access endpoint
  # caCerts: ""

# specify user principal ids to be assiged as cluster members
# clusterMembers:
# - principalName: "local://u-z8zl5"
#   roleTemplateName: "cluster-member"

# monitoring options (optional)
monitoring:
  enabled: false
  # specify which version to install, can be semver range. If version is empty or is semver range, it will pick up the latest version.
  # version: ""
  # specify cutsom values set
  # values:
  #   foo: bar
