cluster:
  name: "mycluster"
  labels: {}
  annotations: {}

# cloud provider name (values can be aws, azure, cloudscale, digitalocean, equinix, exoscale, harvester, linode, nutanix, openstack, outscale, vsphere or custom)
cloudprovider: ""

agentEnvs: []
  # - name: string
  #   value: string

# cloud credential secret name (do not need to be provided if using custom driver)
cloudCredentialSecretName: ""

kubernetesVersion: "v1.24.14+rke2r1"

# Rancher Kubernetes Engine options (Kubernetes distribution)
rke:
  localClusterAuthEndpoint:
    enabled: false
    fqdn: foo.bar.example
    caCerts: ""

# specify user principal ids to be assiged as cluster members
# clusterMembers:
# - principalName: "local://u-z8zl5"
#   roleTemplateName: "cluster-member"

monitoring:
  enabled: false
  # version: ""   # if version is empty or is semver range, the latest version will be used
  # values:       # custom values
  #   foo: bar

nodepools: []
  # - etcd: true
  #   controlplane: true
  #   worker: true
  #   annotations: {}
  #   labels: {}
  #   quantity: 1
  #   paused: false
  #   name: ""
  #   displayName: ""
  #   rollingUpdate:
  #     maxSurge: "1"
  #     maxUnavailable: "5"
  #   machineDeploymentAnnotations: {}
  #   machineDeploymentLabels: {}
  #   region: ""                                # AWS, Azure, Outscale, vSphere
  #   machineImage: ""                          # AWS, Azure, Outscale
  #   instanceType: ""                          # AWS, Azure, Outscale
  #   storageType: ""                           # AWS, Azure, Outscale
  #   sshUser: ""                               # AWS, Azure, vSphere
  #   openPorts:                                # AWS, Azure
  #     - 42/tcp
  #   diskSize: "30"                            # Azure, Outscale, vSphere
  #   tags:                                     # AWS, vSphere
  #     - foo
  #     - bar
  #   blockDurationMinutes: 0                   # AWS spot instance duration in minutes (60, 120, 180, 240, 300, or 360)
  #   deviceName: "/dev/sda1"                   # AWS root device name
  #   encryptEbsVolume: false                   # AWS Encrypt the EBS volume using the AWS Managed CMK
  #   endpoint: ""                              # Optional endpoint URL (hostname only or fully qualified)
  #   iamInstanceProfile: ""                    # AWS IAM Instance Profile
  #   insecureTransport: false                  # Disable SSL when sending requests
  #   createSecurityGroup: true                 # Whether to create `rancher-node` security group. If false, can provide with existing security group
  #   securityGroups: []
  #   keypairName: ""                           # AWS keypair to use
  #   securityGroupReadonly: false              # skip adding default rules to security groups
  #   sshKeyContents: ""                        # AWS file content
  #   subnetId: ""                              # AWS VPC subnet id
  #   monitoring: false                         # AWS flag to enable CloudWatch monitoring
  #   privateAddressOnly: false                 # AWS flag to only use a private IP address
  #   requestSpotInstance: false                # AWS flag to request spot instance
  #   retries: 5                                # AWS retry count for recoverable failures (use -1 to disable)
  #   rootSize: 16                              # AWS root disk size (in GB)
  #   spotPrice: 0.5                            # AWS spot instance bid price (in dollar)
  #   vpcId: ""                                 # AWS VPC id
  #   useEbsOptimizedInstance: false            # AWS create an EBS optimized instance
  #   usePrivateAddress: false                  # AWS force the usage of private IP address
  #   userdata: ""                              # AWS file contents for userdata
  #   zone: a                                   # AWS zone for instance (i.e. a,b,c,d,e)
  #   availabilitySet: "avs-AZURE_PREFIX"       # Azure only
  #   azureEnvironment: AzurePublicCloud        # Azure only
  #   customData: ""                            # Azure only
  #   dockerPort: "2376"                        # Azure only
  #   faultDomainCount: "3"                     # Azure only
  #   managedDisks: true                        # Azure only
  #   networkSecurityGroup: "nsg-AZURE_PREFIX"  # Azure only
  #   noPublicIp: false                         # Azure only
  #   privateIpAddress: ""                      # Azure only
  #   resourceGroup: "rg-AZURE_PREFIX"          # Azure only
  #   staticPublicIp: ""                        # Azure only
  #   subnet: rke2                              # Azure only
  #   subnetPrefix: "192.168.0.0/16"            # Azure only
  #   updateDomainCount: "5"                    # Azure only
  #   usePrivateIp: false                       # Azure only
  #   virtualNetwork: "vnet-AZURE_PREFIX"       # Azure only
  #   diskIops: "1500"                          # Outscale only
  #   cfgparam:                                 # vSphere only
  #     - string
  #   cloneFrom: ""                             # vSphere only
  #   cloudConfig: ""                           # vSphere only
  #   taints:                                   # vSphere only
  #     - effect: string
  #       key: string
  #       timeAdded: string
  #       value: string
  #   contentLibrary: ""                        # vSphere only
  #   cpuCount: ""                              # vSphere only
  #   creationType: ""                          # vSphere only
  #   customAttribute:                          # vSphere only
  #     - string
  #   datastore: ""                             # vSphere only
  #   datastoreCluster: ""                      # vSphere only
  #   diskSize: ""                              # vSphere only
  #   folder: ""                                # vSphere only
  #   hostsystem: ""                            # vSphere only
  #   memorySize: ""                            # vSphere only
  #   network:                                  # vSphere only
  #     - string
  #   pool: ""                                  # vSphere only
  #   sshPort: ""                               # vSphere only
  #   sshUserGroup: ""                          # vSphere only
  #   vappIpallocationpolicy: ""                # vSphere only
  #   vappIpprotocol: ""                        # vSphere only
  #   vappProperty:                             # vSphere only
  #     - string
  #   vappTransport: ""                         # vSphere only
  #   vcenter: ""                               # vSphere only
  #   vcenterPort: ""                           # vSphere only
