# https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
keycloak:
  auth:
    adminUser: user
    adminPassword: Admin1234
    # existingSecret: keycloak-credentials
    # passwordSecretKey: admin-password
  # production: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls: true
  # extraEnvVars:
  #   - name: KEYCLOAK_LOG_LEVEL
  #     value: DEBUG
