name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3.1.0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: latest
      - name: Install Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.7
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.3.1
      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Lint charts
        run: ct lint
