name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CHARTS_DIRECTORIES_ARG: "--chart-dirs charts"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3.1.0
        with:
          # note: important to have chart-testing work (see https://github.com/helm/chart-testing/issues/186)
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.10.1
      - name: Install Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.11
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.3.1
      - name: Add dependency chart repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add jetstack https://charts.jetstack.io
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
      - name: Host charts repository on GitHub Pages
      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed ${CHARTS_DIRECTORIES_ARG} --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Lint charts
        run: ct lint $CHARTS_DIRECTORIES_ARG --target-branch ${{ github.event.repository.default_branch }}
      # TODO: copied from doc, to be tested
      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.4.0
      #   if: steps.list-changed.outputs.changed == 'true'
      # - name: Run chart-testing (install)
      #   run: ct install
