# Continuous Delivery (Packaging)
name: PKG

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CHARTS_DIRECTORIES_ARG: "--chart-dirs charts/applications --chart-dirs charts/backing-services --chart-dirs charts/kube-addons --chart-dirs charts/observability --chart-dirs charts/security --chart-dirs charts/software-factory"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.10.1
