# title: Continuous Delivery (Packaging)
# requirements:
#   - Create manually "gh-pages" branch
#   - Maintain pages files in "gh-pages" branch: index.tpl, placeholder.png
# uses:
#   - https://github.com/helm/chart-releaser-action
#   - https://github.com/halkeye/helm-repo-html
#   - https://github.com/actions/configure-pages

name: PKG

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install Node.js dependencies
        run: npm install
      # ref. https://vitepress.dev/guide/deploy#github-pages
      - name: Build with VitePress
        run: npm run docs:build
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/.vitepress/dist/
      # ref. https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest
      - name: Add dependency chart repositories
        run: ./scripts/add_helm_repo.sh
      - name: Host charts repository on GitHub Pages
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      # important: it needs to be done in the same pipeline as another pages workflow won't be triggered by the pust on the gh-pages branch
      # (tried with a PAT and several options but didn't work)
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs
      - name: DEBUG
        run: |
          ls -alrt .
          ls -alrt docs
      - name: Setup Go environment
        uses: actions/setup-go@v5
      - name: Generate index.html
        run: |
          go install github.com/halkeye/helm-repo-html@v0.2.1
          /home/runner/go/bin/helm-repo-html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Copy docs to website folder
        run: |
          id
          ls -alrt ./_site
          sudo mkdir -p ./_site/docs
          sudo cp -r docs/* ./_site/docs/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
