# ---------------------------------------------------------------------------------------
# Title: Continuous Delivery (Packaging)
#
# Requirements:
#   - Create "gh-pages" branch
#   - In GitHub user Settings, Developer settings, Personal access tokens, Fine-grained tokens, Generate new token
#   - In GitHub repository Settings, Secrets, Actions, New repository secret "USER_GITHUB_PAT" with the token value
#
# Uses:
#   - https://github.com/helm/chart-releaser-action
# ---------------------------------------------------------------------------------------

name: PKG

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.10.1
      - name: Add dependency chart repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add jetstack https://charts.jetstack.io
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
      - name: Host charts repository on GitHub Pages
        uses: helm/chart-releaser-action@v1.4.1
        env:
          # GITHUB_TOKEN can't be used as it won't trigger a workflow run on the push event
          CR_TOKEN: "${{ secrets.USER_GITHUB_PAT }}"
