image:
  repository: ghcr.io/devpro/trackboard
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
  # - name: ""

replicaCount: 1

podAnnotations: {}

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 500m
  #   memory: 512Mi

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  # e.g. traefik
  className: ""
  domain: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  tls:
    enabled: false

startupProbe:
  httpGet:
    path: /healthz
    port: http
  failureThreshold: 10
  periodSeconds: 3

livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

podSecurityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 1000
  # fsGroup: 1000
  # seccompProfile:
  #   type: RuntimeDefault

containerSecurityContext: {}
  # allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: false
  # capabilities:
  #   drop:
  #     - ALL

nodeSelector: {}
tolerations: []
affinity: {}

env:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"
  EVENT_NAME: "DevOpsDay Geneva"
  EVENT_DATE: "May 2026"

# envFrom:
#   - secretRef:
#       name: ""

networkpolicy:
  enabled: false

admin:
  password: ""
